import turtle
def draw_heart():
    heart = turtle.Turtle()
    heart.shape("turtle")
    heart.color("red")
    heart.speed(5)
    heart.pensize(5)
    heart.begin_fill()
    heart.left(140)
    heart.forward(180)
    heart.circle(-90, 200)
    heart.left(120)
    heart.circle(-90, 200)
    heart.forward(180)
    heart.end_fill()
    heart.hideturtle()
def draw_crack():
    crack = turtle.Turtle()
    crack.color("white")
    crack.speed(3)
    crack.pensize(10)
    crack.penup()
    crack.goto(0, 0)
    crack.pendown()
    crack.right(-60)
    crack.forward(70)
    crack.left(90)
    crack.forward(70)
    crack.right(90)
    crack.forward(70)
    crack.left(90)
    crack.forward(50)
    crack.right(90)
    crack.forward(60)
    crack.hideturtle()
draw_heart()
draw_crack()
turtle.exitonclick()
